service: serverless-example

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs16.x

functions:
  main:
    handler: dist/_lambda/download-file/main.handler
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: '{proxy+}'

custom:
  serverless-offline:
    httpPort: 4000